import Link from 'next/link';
import { Bot, Film, Music, ShieldCheck, Sparkles, Video } from 'lucide-react';
import { Button } from '@/components/ui/button';

const proofPoints = [
  {
    icon: Sparkles,
    title: 'Narrative-first workflow',
    description: 'Move from idea to short-form storyboard without stitching tools together by hand.',
  },
  {
    icon: Film,
    title: 'Cinematic scene control',
    description: 'Dial in scripts, images, voice, effects, overlays, and final render timing from one surface.',
  },
  {
    icon: ShieldCheck,
    title: 'Custom Animation Access',
    description: 'Get access to custom animations and assets that make your videos pop and feel unique.',
  },
   {
    icon: Music,
    title: 'Sound Effect Full Control',
    description: 'Easily add and customize sound effects to enhance the impact of your videos.',
   },
];

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="relative min-h-screen overflow-hidden bg-[#f7f8fc] text-slate-950">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_left,rgba(99,102,241,0.16),transparent_34%),radial-gradient(circle_at_bottom_right,rgba(129,140,248,0.18),transparent_30%),linear-gradient(180deg,rgba(255,255,255,0.98),rgba(238,242,255,0.96))]" />
      <div
        className="absolute inset-0 bg-[linear-gradient(rgba(99,102,241,0.06)_1px,transparent_1px),linear-gradient(90deg,rgba(99,102,241,0.06)_1px,transparent_1px)] opacity-60"
        style={{ backgroundSize: '72px 72px' }}
      />

      <div className="relative flex min-h-screen flex-col">
        <header className="border-b border-slate-200/80 bg-white/70 backdrop-blur-xl">
          <div className="mx-auto flex w-full max-w-7xl items-center justify-between px-4 py-5 sm:px-6 lg:px-8">
            <Link href="/" className="flex items-center gap-3 transition hover:opacity-90">
              <span className="inline-flex h-11 w-11 items-center justify-center rounded-2xl bg-indigo-100 text-indigo-600 shadow-[0_0_0_1px_rgba(99,102,241,0.08)]">
                <Video className="h-5 w-5" />
              </span>
              <span>
                <span className="block text-sm font-semibold uppercase tracking-[0.32em] text-slate-500">
                  Auto Video Generator
                </span>
                <span className="block text-base font-medium text-slate-950">
                  Creator studio access
                </span>
              </span>
            </Link>

            <div className="hidden items-center gap-3 sm:flex">
              <Link href="/privacy">
                <Button variant="ghost" className="text-slate-700 hover:bg-indigo-50 hover:text-indigo-700">
                  Privacy
                </Button>
              </Link>
              <Link href="/terms">
                <Button variant="ghost" className="text-slate-700 hover:bg-indigo-50 hover:text-indigo-700">
                  Terms
                </Button>
              </Link>
            </div>
          </div>
        </header>

        <main className="mx-auto flex w-full max-w-7xl flex-1 items-center px-4 py-10 sm:px-6 lg:px-8 lg:py-14">
          <div className="grid w-full gap-6 lg:grid-cols-[minmax(0,1.15fr)_minmax(420px,520px)] lg:gap-10">
            <section className="hidden rounded-[2rem] border border-slate-200/80 bg-white/85 p-8 shadow-[0_24px_80px_-58px_rgba(99,102,241,0.22)] backdrop-blur-md lg:flex lg:flex-col lg:justify-between">
              <div>
                <div className="inline-flex items-center gap-2 rounded-full border border-indigo-100 bg-indigo-50 px-3 py-1 text-xs font-semibold uppercase tracking-[0.28em] text-indigo-600">
                  <Bot className="h-3.5 w-3.5" />
                  AI production engine
                </div>
                <h2 className="mt-6 max-w-xl text-5xl font-semibold leading-tight tracking-[-0.03em] text-slate-950">
                  Build videos that feel edited, not autogenerated.
                </h2>
                <p className="mt-5 max-w-2xl text-base leading-8 text-slate-600">
                  The product is evolving from a simple generator into a proper control room for
                  short-form storytelling. This auth layer is the entry point into that studio.
                </p>
              </div>

              <div className="grid gap-4 md:grid-cols-3 lg:grid-cols-1 xl:grid-cols-2 mt-5">
                {proofPoints.map((item) => {
                  const Icon = item.icon;

                  return (
                    <div
                      key={item.title}
                      className="rounded-3xl border border-slate-200 bg-slate-50/90 p-5"
                    >
                      <span className="inline-flex h-10 w-10 items-center justify-center rounded-2xl bg-indigo-100 text-indigo-600">
                        <Icon className="h-5 w-5" />
                      </span>
                      <h3 className="mt-4 text-lg font-medium text-slate-950">{item.title}</h3>
                      <p className="mt-2 text-sm leading-6 text-slate-600">{item.description}</p>
                    </div>
                  );
                })}
              </div>
            </section>

            <section className="flex items-center justify-center">{children}</section>
          </div>
        </main>
      </div>
    </div>
  );
}

